# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server:
  port: ${port:9998}
security:
  ignored: /metrics,/rest/registrations/*,/rest/registrations,/new-account*,/v2/api-docs,/api-docs/default/*,/images/*,/lib/*,/healthz

spring.oauth2:
  client:
    accessTokenUri: ${sso.tokenUri}
    userAuthorizationUri: ${sso.authorizationUri}
    clientId: ${sso.clientId}
    clientSecret: ${sso.clientSecret}

  resource:
    id: tap
    jwt:
      keyUri: ${sso.tokenKey}

oauth:
  uaa: ${sso.uaaUri}

smtp:
  host: localhost
  port: 25
  protocol: smtp
  username:
  password:
  email: ${sso.email:support@example.com}
  timeout: 5000
  debug: true
  #List of blocked domain. Adding new domain after comma: example.com,foo.com
  forbidden_domains: example.com
  email_name: TrustedAnalytics

redis:
  host: localhost
  port: 6379

authgateway:
  host: ${authgateway.host}

web:
  debug: false

endpoints:
  prometheus.id: metrics
  metrics.id: springmetrics

metrics:
  name: tap_usermanagement_counts
  delay: 15000

spring.profiles.active: cloud,in-memory


logging:
  level:
    org.trustedanalytics: DEBUG
    org.springframework.security: DEBUG

core.org:
  id: defaultorg
  name: default