server:
  port: ${port:9998}
security:
  ignored: /rest/registrations/*,/rest/registrations,/new-account*,/v2/api-docs,/api-docs/default/*,/images/*,/lib/*

spring.oauth2:
  client:
    accessTokenUri: ${sso.tokenUri}
    userAuthorizationUri: ${sso.authorizationUri}
    clientId: ${sso.clientId}
    clientSecret: ${sso.clientSecret}

  resource:
    id: tap
    jwt:
      keyUri: ${sso.tokenKey}

oauth:
  uaa: ${sso.uaaUri}

smtp:
  host: localhost
  port: 25
  protocol: smtp
  username:
  password:
  email: ${sso.email:support@example.com}
  timeout: 5000
  debug: true
  #List of blocked domain. Adding new domain after comma: example.com,foo.com
  forbidden_domains: example.com
  email_name: TrustedAnalytics

redis:
  host: localhost
  port: 6379

web:
  debug: false

app:
   url: ${user.management.uri:}
   console:
       host: dashboard
       useSsl: true

endpoints.health.enabled: true

spring.profiles.active: cloud,in-memory

logging:
  level:
    org.trustedanalytics: DEBUG
    org.springframework.security: DEBUG
